### ISSUE TITLE
Add UCSC beacons with API v. 0.2

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#34]
Links:
http://hgwdev-max.soe.ucsc.edu/cgi-bin/beacon2/query
http://hgwdev-max.soe.ucsc.edu/cgi-bin/beacon2/info
http://hgwdev-max.soe.ucsc.edu/cgi-bin/hgBeacon

**Comment by rohankatyal29** [comment]
Shouldn't this be closed, the UCSC beacon processor has already been implemented ?

**Comment by mcupak** [comment]
That's for 0.1 beacons. 0.2 beacons are still in development, this issue is stalled until things get more stable.

**Comment by mcupak** [comment]
New version here: http://genome.ucsc.edu/cgi-bin/hgBeacon

It should replace the old beacons when ready.
