### ISSUE TITLE
List beacons in the client

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#44]
Add a page providing a list of beacons, their organizations and aggregate flag on a separate page in the client.

**Comment by rohankatyal29** [comment]
Hasn't this already been implemented?
![screen shot 2015-03-08 at 8 50 31 pm](https://cloud.githubusercontent.com/assets/2452426/6546296/d0587ef0-c5d4-11e4-84a9-7b5359a4bff3.png)

**Comment by mcupak** [comment]
Not quite. I wanted to add a list of organizations and the corresponding beacons below the map on the beacon-map page as well.

**Comment by mcupak** [comment]
[Beacon map page](https://github.com/mcupak/beacon-of-beacons/blob/master/bob-js-client/src/main/webapp/map.html) should contain a list of beacons below the map. The list of beacons can be obtained [here](https://github.com/mcupak/beacon-of-beacons/blob/master/bob-js-client/src/main/webapp/map.html) (JSON is the default output).

Beacons should be grouped by organizations, which are sorted alphabetically. It should be a table-like layout made of divs, something like this:

```
+-------------------+--------------------------------+-----------------+
| Organization      | Beacon                         | Aggregator      |
+-------------------+--------------------------------+-----------------+
|                   |  Leiden Open Variation         |       no        |
|       UCSC        |  Uniprot                       |       no        |
|                   |  ....                          |                 |
```

@rohankatyal29 Do you want to take a stab at this little feature?

**Comment by rohankatyal29** [comment]
Yeah, I am on it. 
The beacon map page and list of beacons link are pointing towards the same url?

**Comment by mcupak** [comment]
My bad, here's the correct link: http://beacon-dnastack.rhcloud.com/rest/beacons

**Comment by rohankatyal29** [comment]
fa5f1f234428cd87796daafe4590dc5a329fe181
