### ISSUE TITLE
Update Node.js BDK to Beacon 0.2 API

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#51]
Adapter: https://github.com/mcupak/beacon-of-beacons/tree/master/beacon-adapters/beacon-nodejs
Docs: http://mcupak.github.io/beacon-of-beacons/beacons.html#nodejs
API 0.2: https://docs.google.com/document/d/1hFVqmPDKAs2Tacqta98oIPqUOKlHghmuJD8DtYLQFKw/edit?usp=sharing

Change /query and /info endpoints to generate data in the form according to the new API version.

**Comment by rohankatyal29** [comment]
@mcupak: This commit has been included in the pull request for the python BDK
