### ISSUE TITLE
Update Python BDK to Beacon 0.2 API

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#53]
Adapter: https://github.com/mcupak/beacon-of-beacons/tree/master/beacon-adapters/beacon-python
Docs: http://mcupak.github.io/beacon-of-beacons/beacons.html#python
API 0.2: https://docs.google.com/document/d/1hFVqmPDKAs2Tacqta98oIPqUOKlHghmuJD8DtYLQFKw/edit?usp=sharing

Change /query and /info endpoints to generate data in the form according to the new API version.

**Comment by rohankatyal29** [comment]
@mfiume & @mcupak, I have a few doubts regarding this issue. I have made some edits to beacon.py :
![screen shot 2015-03-12 at 6 47 14 pm](https://cloud.githubusercontent.com/assets/2452426/6618379/6f49de26-c8e8-11e4-88be-badabc96c950.png)

* In the beacon variable I have removed the description field and added the api version as the description field is not a required field in the documentation.

* In the query method I have added a dataset variable. The documentation states that
> "If no dataset is provided, it is to be interpreted as querying all datasets, i.e. the response should represent the union of querying each dataset" 

how can get this union? 

* Allele is not a required field, in a case when the user doesn't provide the allele won't the response be blank for the allele field ?

* In the response variable I have only included the exists field as it is the only required one

**Comment by mcupak** [comment]
Ad datasets: The list is what is exposed under "datasets" field on /info, see the draft document. Whatever is under /info translates to properties of the beacon object.

Ad alleles: Let's assume allele is a required field.

In general, the adapter should provide all the fields (not only the required ones) - it's easier for people to remove the fields they don't need than look up the fields they need to add somewhere else. You can mark optional fields as "optional" with a comment.

**Comment by rohankatyal29** [comment]
So in the case when the dataset parameter is empty, the dataset_id parameter in the response will be whatever the beacon object specifies for the dataset parameter?

**Comment by mcupak** [comment]
Let's default to one. In other words, if there are 2 datasets under /info and no dataset is specified in the request, the response will include ID of the first one in the list.

**Comment by rohankatyal29** [comment]
@mcupak : can you please review the code

**Comment by mcupak** [comment]
A few comments:
- On /query, "observed" field should be integer, not string.
- On /query under "response" > "alleles" > "allele", use the value from "query" > "allele".
- Remove "multiple" and  "datasets" field from within "datasets" array on /info (deprecated).
- Instead of including the whole beacon object in the query response, could you only include its ID (see BeaconResponseResource in the draft document)?
- Can you replace those "string" values with something  specific like "example"? Just so that it does not confuse people as it's also a type.
- Can you remove "rest" from the paths? E.g. instead of /beacon-python/rest/info, we would have /beacon-python/info.
- Can you add a sample welcome page to /beacon-python so that it doesn't return internal server error there?
- Can you return 404 instead of internal server error when a nonexistent URL is provided? (e.g. /beacon-python/test)

Thanks!

**Comment by rohankatyal29** [comment]
will take care of all those and replicate the same for node and java

**Comment by mcupak** [comment]
Fantastic. Thanks!
