### ISSUE TITLE
Add a page generating JS snippet to query selected beacons

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#58]
A new page should be added to the client. On that page, a user should be allowed to select a subset of beacons and click a button. Based on this selection, the click on the button will generate a snippet of Javascript/HTML, which would execute a query to the selection of beacons. This snippet should be isolated and embeddable into 3rd party web sites.

This snippet should invoke a call to the backend, which is already capable of querying multiple beacons in parallel (via beacon parameter).

For example, the following query is run against amplab and clinvar beacons:
http://beacon-dnastack.rhcloud.com/rest/responses?chrom=14&pos=106833421&allele=A&beacon=[amplab,clinvar]

**Comment by rohankatyal29** [comment]
This is what I understood, let me know if I am wrong: 
The user should be able to select the beacons for eg: amplab and clinvar. This would generate a snippet which would have a form (HTML and JS) and will only query amplab and clinavr.
![screen shot 2015-03-11 at 7 02 44 am](https://cloud.githubusercontent.com/assets/2452426/6588785/b742df16-c7bc-11e4-9889-9fa2c315f69e.png) On submitting this form queries of the type http://beacon-dnastack.rhcloud.com/rest/responses?chrom=14&pos=106833421&allele=A&beacon=[amplab,clinvar] will be generated. The form will NOT query other beacons, only the ones selected by the user?

**Comment by mcupak** [comment]
@mfiume WDYT?

**Comment by mfiume** [comment]
@mcupak and @rohankatyal29:

The widget should not show a query interface. Rather it should show the results interface. The query will be specified by the page that embeds it.

Configuring the widget
1. A user wishing to embed this widget visits widget.beacon.com. 
2. This user is presented a list of beacons from which to choose from
3. The widget is configured, which generates embeddable code. Something of the form

<script src=“dnastack.com/beacon/bobby.js”>
	(function() {
		var beacons = [“ICGC”,”EBI”];
		// change this line
		bobby.writeIFrame(chr1,1232,A,hg19,beacons);
	})();
</script>

where var beacons is set to whatever beacons were selected in step 2.

bobby.writeIFrame writes an IFrame that essentially shows the results page of the regular Beacon of Beacons, but restricted only to to the beacons specified in step 2.

**Comment by mcupak** [comment]
A few possibly helpful links on why we want to use this iframe/script approach:
- http://prettyprint.me/prettyprint.me/2009/05/30/widgets-iframe-vs-inline/
- http://codeutopia.net/blog/2012/05/26/best-practices-for-building-embeddable-widgets/
- http://alexmarandon.com/articles/web_widget_jquery/

Also, we want responsive/fluid iframes:
- http://embedresponsively.com/
- http://www.bymichaellancaster.com/blog/fluid-iframe-and-images-without-javascript-plugins/

**Comment by rohankatyal29** [comment]
This is what I have done till now: 
1. User selects the beacons he wants to generate a widget for: 
![screen shot 2015-03-11 at 9 21 48 pm](https://cloud.githubusercontent.com/assets/2452426/6600270/a746c780-c834-11e4-9d9c-8e834cfeb743.png)

2. After clicking on generate snippet, a modal comes over with an option to copy the code: 
![screen shot 2015-03-11 at 9 23 28 pm](https://cloud.githubusercontent.com/assets/2452426/6600308/e03defe6-c834-11e4-8442-0492badc3684.png)

3. The code embeds a form with the associated JS and performs queries of the form: 
http://beacon-dnastack.rhcloud.com/rest/responses?chrom=14&pos=106833421&allele=A&beacon=[amplab,clinvar]
![screen shot 2015-03-11 at 9 26 56 pm](https://cloud.githubusercontent.com/assets/2452426/6600408/5faa5ec2-c835-11e4-9234-6598bc45efb7.png)

and returns results in JSON.

I'll work on this to change it accordingly

**Comment by rohankatyal29** [comment]
I'll remove the form and go through the links to change this code

**Comment by rohankatyal29** [comment]
@mcupak & @mfiume 
Please have a look at the current implementation and let me know WDYT: 

(NOTE: url of bobby.js needs to be changed accordingly in generate-snippet.js )

1. User selects the beacons: 
![screen shot 2015-03-12 at 2 16 12 am](https://cloud.githubusercontent.com/assets/2452426/6606464/d077984a-c85d-11e4-9abd-ac23d2613249.png)

2. Modal with the code snippet pops up: 
![screen shot 2015-03-12 at 2 17 18 am](https://cloud.githubusercontent.com/assets/2452426/6606511/fb9322ec-c85d-11e4-95dc-dcf737af16ae.png)

3. The code snippet generates a fluidic IFrame and displays the query page on dnastack.com: 
![screen shot 2015-03-12 at 2 18 55 am](https://cloud.githubusercontent.com/assets/2452426/6606527/274c41e8-c85e-11e4-9fee-9bdaa3276e65.png)

![screen shot 2015-03-12 at 2 19 34 am](https://cloud.githubusercontent.com/assets/2452426/6606540/3e86c176-c85e-11e4-9721-3ae395117184.png)

**Comment by mfiume** [comment]
Looks great @rohankatyal29 and @mcupak. Instead of commenting out the writeIframe line, perhaps this would be better:

//TODO: set these variables as per: https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/beacon.avdl

var chromosome = 1;
var position = 1;
var allele = "A";
var genome = "hg19";

writeIframe(chromosome,....

**Comment by mfiume** [comment]
Also, because the IFrame is going to be embedded into other sites (with their own menus and such), it should only show the YES/NO answers and the blue, green, yellow, red, and cyan elements just above them.

**Comment by mcupak** [comment]
@rohankatyal29 I like this a lot. Please submit a PR.

Just two details:
- Change the hardcoded 'src=\"http://localhost:8080/bob-js-client/js/bobby.js\"' URL to work with this: http://dnastack.com/ga4gh/bob/.
- The "copy snippet" button does not work for me (Firefox 36.0/Linux) - can you check that as well please?

Thanks.

**Comment by rohankatyal29** [comment]
@mfiume - I have made the necessary changes in the function and the IFrame only displays the results now: 
![screen shot 2015-03-12 at 11 41 09 am](https://cloud.githubusercontent.com/assets/2452426/6613037/be3322a4-c8ac-11e4-985a-73031c29cf2b.png)
@mcupak : The hardcoded src has been changed to work with the url you mentioned, but the file path will need to be accordingly changed in js/generate-snippet.js  
![screen shot 2015-03-12 at 11 52 51 am](https://cloud.githubusercontent.com/assets/2452426/6613135/581d4380-c8ae-11e4-819d-1b41a24fe97b.png)
I wasn't able to replicate the copy code error in firefox for linux, it's working for me :/

I have created a PR as well.

**Comment by mcupak** [comment]
Very nice. PR merged, resolving.

**Comment by rohankatyal29** [comment]
:+1:
