### ISSUE TITLE
Use 0-based coordinates

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#60]
A backend issue. The note in the client should be updated as well.

**Comment by rohankatyal29** [comment]
I found the following pseudo code to convert 0-based coordinates to 1-based coordinates:
>if (type=SNV) {start=start+1; end=end;}
>if (type=DEL) {start=start+1; end=end;}
>if (type=INS) {start=start; end=end+1;}

This is what I read in the documentation:
> Any string of nucleotides A,C,T,G or D, I for deletion and insertion. For compatibility with conventions set by some of the existing beacons, DEL and INS identifiers are also accepted
 
I don't know how to figure out which conversion formula to use?

**Comment by mcupak** [comment]
It's actually quite simple - we're using 1-based positions now, so we just need to decrement by 1 everywhere this is used. Unfortunately, there's quite a few places. I'll update this myself.
