### ISSUE TITLE
Provide a way to initialize the database with public beacons

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#68]
One way to do this is by using [Maven SQL plugin](http://mojo.codehaus.org/sql-maven-plugin/). Investigate if the plugin can be configured to use the datasource from the project (without using static database connection configuration) and work in a Hibernate-friendly way (particularly WRT schema changes). If not, [Hibernate's own mechanism](http://stackoverflow.com/questions/673802/how-to-import-initial-data-to-database-with-hibernate) should be used instead.

Prerequisite: [#16](https://github.com/mcupak/beacon-of-beacons/issues/16).

EDIT: Better description of the issue.

**Comment by mcupak** [comment]
This is ready to be implemented. The data is currently initialized using `com.dnastack.bob.util.DatabaseInitializer`, which should be replaced.

**Comment by mcupak** [comment]
@rishabhsethi Are you working on this issue or is it free to take?

**Comment by rishabhsethi** [comment]
@mcupak I am really sorry. I am a little preoccupied. Not working on it right now. Will try it in a few days if it is still open. Please consider it open.

**Comment by mcupak** [comment]
@rishabhsethi No worries. There were other people asking to work on the issue, so I'm just checking if it's taken. Take your time.

**Comment by mcupak** [comment]
Done.
