### ISSUE TITLE
Add SolveBio beacons

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#73]
https://docs.solvebio.com/v1.0/docs/api-dataset-beacon

**Comment by mcupak** [comment]
Deferring as these beacons are not public (API key required).

**Comment by davecap** [comment]
Hello! Our current and future beacon endpoints should be fully open for querying without any API key. If not, I'll look into it!

**Comment by mcupak** [comment]
Indeed, I did not notice that. Thank you for the info!

**Comment by mcupak** [comment]
Beacons have been added to the network: http://beacon-network.org/#/beacons/directory

This includes 21 beacons + 1 aggregating beacon. The datasets not marked as genomic don't really provide a useful response for the beacon endpoint, and thus were not included.
