### ISSUE TITLE
Beacon widget doesn't render properly

### ISSUE THREAD

**Issue by alyh** [mcupak/beacon-of-beacons#80]
The beacon widget is cut off and does not render properly, see this screenshot:

![screen shot 2015-04-14 at 3 16 04 pm](https://cloud.githubusercontent.com/assets/1329372/7145307/54da7092-e2b9-11e4-9c17-18b7f75fddc9.png)

From that view, you can't scroll up but you can scroll down and right.

A fiddle to illustrate the problem: http://jsfiddle.net/ata7jz1b/1/

**Comment by mcupak** [comment]
@alyh I wasn't able to reproduce this. What browser are you using?

Does it happen e.g. on this URL? http://dnastack.com/ga4gh/bob/query.html?beacon=all&ref=all&chrom=1&pos=179393691&alt=A

**Comment by alyh** [comment]
That url is fine, I added a fiddle that has the same problem for me. I tested with Chrome and Safari

http://jsfiddle.net/ata7jz1b/1/

**Comment by mcupak** [comment]
Oh, I see. I will look into that. Thank you!

**Comment by mcupak** [comment]
Beacon of Beacons client has been replaced by the [Beacon Network](http://beacon-network.org/), which will contain a new widget. Closing.
