### ISSUE TITLE
Make REST API accessible over SSL/TLS

### ISSUE THREAD

**Issue by mcupak** [mcupak/beacon-of-beacons#84]

**Comment by marcofalcioni** [comment]
Thanks - we are eagerly awaiting for this to become available. 
Cheers.

**Comment by marcofalcioni** [comment]
Hello, we were wondering if there was any progress to resolve this issue.
Thanks.

**Comment by mcupak** [comment]
@marcofalcioni Sorry, not yet. I'll try to resolve this next week.

**Comment by marcofalcioni** [comment]
Hi @mcupak, any news on this? It would be great if we could use it in our July release.

**Comment by marcofalcioni** [comment]
Hi @mcupak - any updates? Thanks

**Comment by mcupak** [comment]
https://beacon-network.org/api/

Sorry this took so long, we ran into problems with our certificate provider.

**Comment by marcofalcioni** [comment]
thanks!
