### ISSUE TITLE
New UI - issue when querying (first time)

### ISSUE THREAD

**Issue by prota** [mcupak/beacon-of-beacons#99]
Hi, I've noticed some problems when I try to query (first query). I've been able to reproduce the problem at different days, always being the first query. After that it works successfully.
The issue shows 'apparently', from the browser, as the system just search a set of beacons but checking javascript console it logs next errors (1). Hope it helps!

Thank you, 

Joan

(1)

Error while querying BN beacons: GIGAScience #2,Google - 1000 Genomes Project,Google - 1000 Genomes Project Phase 3,Google - Illumina Platinum Genomes,Google Genomics Public Data...vendor-61435a2630.js:33 

Error while querying BN beacons: EBI - 1000 Genomes Project, UK10K, GoNL, EVS, GEUVADIS, UMCG Cardio GenePanel,European Genome-phenome Archive,ExAC,GIGAScience,GIGAScience #1
.
etc.
.

**Comment by mcupak** [comment]
Nice catch, Joan! I was able to reproduce the issue, we will look into it shortly.

**Comment by prota** [comment]
I think it has been solved, isn't it? If so feel free to close. Thanks!
